name: oee_mobile
description: OEE Mobile Application
version: 2.1.0+1
versionName: "Point85 OEE Mobile Application"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# HTTP    
  http: ^1.2.2

  # localization
  intl: any

  # key store persistence
  shared_preferences: ^2.3.2

  # date time picker
  datetime_picker_formfield_new: ^2.1.0  
  
  # tree view
  arborio: ^1.0.1
  
  # asynch provider
  flutter_riverpod: ^2.5.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # icon folder
    - assets/icons/
    # app localizations
    - lib/l10n/  
    
flutter_intl:
  enabled: true
  # Disable metadata validation
  validate_metadata: false    
