name: oee_mobile
description: OEE Mobile Application
version: 2.0.0+1
versionName: "Point85 OEE Mobile Application"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# HTTP    
  http: ^1.2.2

  # localization
  intl: any

  # key store persistence
  shared_preferences: ^2.3.2

  # date time picker
  datetime_picker_formfield_new: ^2.1.0  
  
  # tree view
  arborio: ^0.3.0-beta
  
  # asynch provider
  #provider: ^6.1.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Point85_48.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/Point85_48.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/Point85_48.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/Point85_72.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # icon folder
    - assets/icons/
